### ISSUE TITLE
Reconciliation response: entity name should be a string

### ISSUE THREAD

**Issue by fsteeg** [rg-mpg-de/skohub-reconcile#3]
When we reconcile, e.g. with:

`curl --data 'queries={"q1":{"query":"Bank"}}' http://localhost:3000/rg-mpg-de/polmat`

The candidate names are objects:

```json
"name": {
  "de": "Banken",
  "nl": "Banken",
  "en": "Banks"
}
```

But according to the reconciliation protocol, an entity's `name` [is a string](https://reconciliation-api.github.io/specs/latest/#dfn-entity).

This causes problems both in the [testbench](https://github.com/reconciliation-api/testbench) (where the service can be loaded successfully, but we get an error when we actually reconcile) and OpenRefine (which already hangs when we add the service, since it does a probing reconciliation request to suggest types).

**Comment by awagner-mainz** [comment]
Right. Given that from the point of view of skohub-vocabs, we don't know what the preferred language is (in fact, we don't know which languages there are at all), are there any suggestions, how to pick or build a single string? Otherwise, just take the first one?

**Comment by acka47** [comment]
I guess it would make sense to provide different endpoints for different language, like Wikidata does, see https://wikidata.reconci.link/:

> Use the following URL in OpenRefine: https://wikidata.reconci.link/en/api.
>
> Replacing "en" by another language code will display items and properties in your language, when they are available.
