### ISSUE TITLE
Improve "view" template in manifest?

### ISSUE THREAD

**Issue by awagner-mainz** [rg-mpg-de/skohub-reconcile#7]
In controller.js, we currently have a string with hardcoded server and path names (incl. "skohub.io" and "w3id.org") for the view template value of the reconciliation manifest:

https://github.com/rg-mpg-de/skohub-reconcile/blob/bdb5fb4661ef0c3ed09c3f6f8ed6c2a1d51e0845/src/controller.js#L51

Maybe we can use the `@prefix + subject` from the ttl file somehow instead?

That would be more correct, closer to the vocabulary's author's intentions and also more flexible.

**Comment by fsteeg** [comment]
This causes 404 links (like [this](https://skohub.io/rg-mpg-de/polmat/heads/main/w3id.org/rg-mpg-de/polmat/https://w3id.org/rg-mpg-de/polmat/n01.4esp.7.c.02)) for candidates and matched entries when using the service in OpenRefine.

**Comment by awagner-mainz** [comment]
Fixed by 17f6a11.
